### ISSUE TITLE
How about the kernel source?

### ISSUE THREAD

**Issue by 18712886438** [cryscript/android_device_zuk_z2_plus#1]
Looking for your  kernel source here and it is better if you can upload the device tree with infomation of mine or silence :)

**Comment by cryscript** [comment]
Kernel source will be uploaded later.
And I don't understand that you mean "it is better if you can upload the device tree with infomation of mine or silence".
You mean that I need write that I used your commits and commits from other people?
This device tree includes fixes from Flourmo, Davide D M, Your, Oneplus device commits and my commits.

**Comment by 18712886438** [comment]
Well. it doesn't matter. Happy to see your contribution to z2. By the way my kernel source does not here . It has been upload to coding.net

**Comment by cryscript** [comment]
Thank you and all those involved in  creating ROMs for this device! Together we can do more.
I will upload kernel today or tomorrow.

**Comment by cryscript** [comment]
CallMESuper, do you have telegram messenger? Can you join in this group?
https://telegram.me/joinchat/BD1XbQqVNhOnhBLP2_9Ayw
Let's create good ROM and share experience.

and another link to join in group
http://forum.xda-developers.com/zuk-z2-pro/help/telegram-zuk-z2-developers-modders-t3482796

**Comment by 18712886438** [comment]
Yes. I have. But I am quite busy recently.  Once I get time I will join the group to make good rom together. :)

**Comment by mnemonyc** [comment]
I would help you in this work! I have z2plus and I would like to have a great nougat rom!

**Comment by cryscript** [comment]
https://telegram.me/joinchat/BD1XbQqVNhOnhBLP2_9Ayw
https://telegram.me/joinchat/BD1XbQqVNhMy9gEZMFE-qQ
Someone of this link must be working. Join in group, we all trying create good ROM
